export { default as getOffers } from './getOffers'
export { default as getOfferBySlug } from './getOfferBySlug'
export { default as getServices } from './getServices'
export { default as getServiceBySlug } from './getServiceBySlug'
export { default as getGenericPage } from './getGenericPage'
export { default as getCategories } from './getCategories'
export { default as getCategoryBySlug } from './getCategoryBySlug'
